### ISSUE TITLE
Please clarify the license

### ISSUE THREAD

**Issue by voxik** [ruby/net-protocol#28]
The [license file](https://github.com/ruby/net-protocol/blob/master/LICENSE.txt) contains BSD-2-Clause license, while gemspec specifies [Ruby OR BSD-2-Clause](https://github.com/ruby/net-protocol/blob/2d3c4b43a837a616e5853f807cde63aaffbcd280/net-protocol.gemspec#L20). Assuming the latter is correct, how to capture this information? Is COPYING file similar to Ruby the way to go?

**Comment by hsbt** [comment]
Fixed at https://github.com/ruby/net-protocol/commit/0d0c9f372b7e571c9b446caead6af8f9386cb3ef
